all:
	make debug
flip:
	python3 HW-3.py
flip_multi:
	python3 HW-3.py --multi_process
plot:
	python3 HW-3.py --plot
debug:
	python3 HW-3.py --debug --plot --multi_process
verbose:
	python3 HW-3.py --verbose --plot --multi_process
multi_process:
	python3 HW-3.py --multi_process
save:
	python3 HW-3.py --debug > output.txt
kamilla:
	python3 HW-3_adaboost.py --debug --plot
help:
	python3 HW-3.py --help
